// GENERATED BY CODE! DO NOT MODIFY!
using UnityEngine;
namespace SFX.Visual
{
    [System.Serializable]
    public class Sounds
    {
        public AudioClip touchBallClip;
        public AudioClip fillYarnItemClip;
        public AudioClip completeBoxClip;
        public AudioClip ropeShakeClip;

    }
}